general.import = ["/Users/rozag/configs/alacritty-themes/themes/monokai_pro.toml"]
general.live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#858585"
duration = 100

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 12.1

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "HideOtherApplications"
key = "H"
mods = "Command|Alt"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
chars = "^[[C-Tab"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "^[[C-S-Tab"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "^[[A-1"
key = "Key1"
mods = "Option"

[[keyboard.bindings]]
chars = "^[[A-2"
key = "Key2"
mods = "Option"

[[keyboard.bindings]]
chars = "^[[A-c"
key = "C"
mods = "Option"

[[keyboard.bindings]]
chars = "^[[M-S-h"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "^[[A-q"
key = "Q"
mods = "Option"

[[keyboard.bindings]]
chars = "^[[A-S-k"
key = "K"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "^[[M-l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "^[[M-s"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "^[[M-S-s"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "^[[M-z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "^[[M-S-z"
key = "Z"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "^[[M-/"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
chars = "^[[M-Return"
key = "Return"
mods = "Command"

[mouse]
hide_when_typing = false

[scrolling]
history = 20000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
